# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-29 04:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shr', models.CharField(max_length=50)),
                ('shdh', models.CharField(max_length=11)),
                ('sheng', models.IntegerField()),
                ('shi', models.IntegerField()),
                ('xian', models.IntegerField()),
                ('info', models.CharField(max_length=100)),
                ('isChecked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pid', models.IntegerField()),
                ('path', models.CharField(max_length=20)),
                ('isDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Citys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('level', models.IntegerField()),
                ('upid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('store', models.IntegerField()),
                ('info', models.TextField()),
                ('pic_url', models.CharField(max_length=100)),
                ('status', models.IntegerField(default=0)),
                ('clicknum', models.IntegerField(default=0)),
                ('ordernum', models.IntegerField(default=0)),
                ('addtime', models.TimeField(auto_now_add=True)),
                ('cateid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.Cates')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=77)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=100, null=True)),
                ('sex', models.CharField(choices=[(1, '男'), (0, '女')], max_length=1, null=True)),
                ('age', models.IntegerField(null=True)),
                ('pic_url', models.CharField(max_length=100, null=True)),
                ('status', models.IntegerField(default=0)),
                ('addtime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='goodsid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.Goods'),
        ),
        migrations.AddField(
            model_name='cart',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.Users'),
        ),
        migrations.AddField(
            model_name='address',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.Users'),
        ),
    ]
