# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-29 13:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shr', models.CharField(max_length=50)),
                ('shdh', models.CharField(max_length=11)),
                ('shdz', models.CharField(max_length=100)),
                ('buytype', models.CharField(max_length=10)),
                ('wl', models.CharField(max_length=10)),
                ('totalprice', models.FloatField()),
                ('addtime', models.DateTimeField(auto_now_add=True)),
                ('buytime', models.DateTimeField(null=True)),
                ('status', models.IntegerField(default=0)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.Users')),
            ],
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodsid', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('pic_url', models.CharField(max_length=100)),
                ('num', models.IntegerField()),
                ('orderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.Order')),
            ],
        ),
    ]
